name: GitHub Stats Cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs every 24 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: QWavey
          # Options: default, visual_studio, github, github_dark, solarized_light, ocean_dark, etc.
          THEME: github_dark
