name: Update Trophies
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: QWavey
          OUTPUT_PATH: github-trophies.svg   # <-- Added this explicit file path
